Fix/quick order uo m issue
clouda-inc/quickorder pull request #28
Opened 2022-03-23 09:56 UTC by devinkulanjith

#### What does this PR do? \*
* Add UoM filed in quick order search result

#### How to test it? \*
[Workspace](https://productsearch--sbdsefprod.myvtex.com/quickorder?__bindingAddress=catalog2.sef.ao.sbd-prod.com/en-US/catalog-global)

2022-03-23 21:17 UTC, Jayendra88 requested changes

2022-03-23 21:17 UTC, Jayendra88 commented on react/AutocompleteBlock.tsx
> +                      minValue={1}
this should be moq

2022-03-23 21:17 UTC, Jayendra88 commented on react/AutocompleteBlock.tsx
> +                      maxValue={10000000}
we should put the same values in product summary quantity selector

2022-03-24 04:38 UTC, devinkulanjith commented on react/AutocompleteBlock.tsx
> +                      minValue={1}
In sef-quantity-selector same logic is used , minvalue is taken as 1

2022-03-24 04:38 UTC, devinkulanjith commented on react/AutocompleteBlock.tsx
> +                      maxValue={10000000}
In sef-quantity-selector same logic is used , minvalue is taken as 1

2022-03-24 17:58 UTC, merged