Fix/quick order popup
clouda-inc/quickorder pull request #32
Opened 2022-06-02 07:54 UTC by NAVODYA123

#### What does this PR do?

-  Remove go-to-checkout button from quick order add-to-cart popup

#### How to test it? 

1. Visit the given [workspace](https://cartdemo--sbdsefuat.myvtex.com/quickorder?__bindingAddress=catalog.sef.ao.sbd-nonprod.com/en-US/catalog-global)
2. Sign in to the account 
3. Select a sold to select account
4. Navigate to quick order page and scroll to the bottom of the page where the product search is placed
5. Search for product `av25 - 73483-00001` or any other product and select it
6. Click on the Add to Cart button
7. A pop up will be displayed at the bottom of the page(the clickable button in the popup is removed hence, it is not visisble)

2022-06-07 01:01 UTC, Jayendra88 requested changes

2022-06-07 01:01 UTC, Jayendra88 commented on manifest.json
> +  "vendor": "sbdsefuat",
Change vendor name to `sbdsefprod`

2022-06-07 01:01 UTC, Jayendra88 commented on react/AutocompleteBlock.tsx
> +      // action = success
Remove commented line

2022-07-06 08:26 UTC, NAVODYA123 commented on manifest.json
> +  "vendor": "sbdsefuat",
done

2022-07-06 08:41 UTC, NAVODYA123 commented on react/AutocompleteBlock.tsx
> +      // action = success
done

2022-07-06 15:05 UTC, Jayendra88 approved these changes

2022-07-06 15:05 UTC, merged