Bug fix: infinite loading state
clouda-inc/quickorder pull request #58
Opened 2024-03-19 04:11 UTC by pasindu-clouda

#### What does this PR do? \*

-bug fix: infinite loading state

workspace: [https://quickordervalidatebutton--sbdsefuat.myvtex.com/](https://quickordervalidatebutton--sbdsefuat.myvtex.com/)

2024-03-19 04:35 UTC, sahanljc requested changes
Please update the CHANGELOG.

2024-03-19 04:35 UTC, sahanljc commented on react/utils/index.ts
> +      skuRefId: data.getSkuRefIdWithCustomerPart.refId.toUpperCase(),
Is there a specific reason for changing the ref ID to uppercase, as usually this kind of transform has not been used in the solution?

2024-03-19 05:41 UTC, pasindu-clouda commented on react/utils/index.ts
> +      skuRefId: data.getSkuRefIdWithCustomerPart.refId.toUpperCase(),
there was a infinite loading state and graphql error when user enter sku in lower case, because all the stanly skus are in that format on the admin catalog, i thought of doing this and it fixes the bug

2024-03-21 11:09 UTC, sahanljc approved these changes

2024-03-21 11:10 UTC, merged