Feature: Display Itemized Country of Origin Information
clouda-inc/quickorder pull request #74
Opened 2024-06-21 10:37 UTC by pasindu-clouda

#### What does this PR do? \*

- add itemized country of origin details

workspace: [https://quickorderdev--sbdsefuat.myvtex.com](https://quickorderdev--sbdsefuat.myvtex.com/quickorder?__bindingAddress=catalog.sef.ao.sbd-nonprod.com/en-US/catalog-global)

2024-06-26 10:53 UTC, neeshsilva requested changes
Update the change log.

2024-06-26 10:53 UTC, neeshsilva commented on react/TextAreaBlock.tsx
> +  // const [countryOfOriginList, setCountryOfOriginList] = useState<any>([])
Remove unwanted commented code lines.

2024-06-26 10:53 UTC, neeshsilva commented on react/components/ReviewBlock.tsx
> +        console.log('itm', itm)
Remove the console logs.

2024-06-26 11:03 UTC, Nadeera-Gayashan requested changes

2024-06-26 11:03 UTC, Nadeera-Gayashan commented on node/resolvers/search/index.ts
> +  },
can't we narrow down the search using 'where' condition? also reduce the page size at least to 10.

2024-06-26 11:03 UTC, Nadeera-Gayashan commented on react/TextAreaBlock.tsx
> +
remove unwanted comments

2024-06-26 11:03 UTC, Nadeera-Gayashan commented on react/utils/const.ts
> +export const COO_DATA = [
why these data?

2024-06-26 11:12 UTC, pasindu-clouda commented on react/utils/const.ts
> +export const COO_DATA = [
oh we can remove those

2024-06-26 11:15 UTC, pasindu-clouda commented on node/resolvers/search/index.ts
> +  },
ahh okay

2024-06-27 04:20 UTC, Nadeera-Gayashan requested changes

2024-06-27 04:20 UTC, Nadeera-Gayashan commented on react/TextAreaBlock.tsx
> +            countryOfOriginList.find(
null check?

2024-06-27 04:20 UTC, Nadeera-Gayashan commented on react/TextAreaBlock.tsx
> +            countryOfOriginList.find(
null check?

2024-06-27 04:20 UTC, Nadeera-Gayashan commented on react/components/ReviewBlock.tsx
> +            countryOfOriginList.find(
null check?

2024-06-27 11:05 UTC, Nadeera-Gayashan commented on react/components/ReviewBlock.tsx
> +            countryOfOriginList.find(
countryOfOriginList?.find

2024-06-27 11:18 UTC, Nadeera-Gayashan requested changes

2024-06-27 11:18 UTC, Nadeera-Gayashan commented on react/TextAreaBlock.tsx
>      const data = tableData.flatMap((item: any) => {
Here

2024-06-27 11:25 UTC, Nadeera-Gayashan approved these changes

2024-06-27 11:25 UTC, merged